# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hackathon
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


collections:
  pages:
    output: true
    permalink: /:path/
  indicators:
    output: true
  goals:
    output: true

prose:
  ignore: ['/assets', '/_includes', '/_layouts', '/scripts', '/sass' ]
  metadata:
    _indicators:
      - name: "nazwa_wskaznika"
        field:
            element: text
            label2: "Name of the indicator"
            scope: global
      - name: "zadanie"
        field:
            element: textarea
            label2: "Target"
            scope: global
      - name: "definicja"
        field:
            element: textarea
            label2: "Definition"
            scope: global
      - name: "jednostka_prezentacji"
        field:
            element: text
            label2: "Unit"
            scope: global
      - name: "dostepne_wymiary"
        field:
            element: textarea
            label2: "Available dimensions"
            scope: global
      - name: "wyjasnienia_metodologiczne"
        field:
            element: textarea
            label2: "Methodological explanations"
            scope: global
      - name: "zrodlo_danych"
        field:
            element: text
            label2: "Source of data"
            scope: global
      - name: "czestotliwosc_dostępnosc_danych"
        field:
            element: textarea
            label2: "Data availability"
            scope: global
      - name: "uwagi"
        field:
            element: textarea
            label2: "Notes"
            scope: global
