# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hackathon EU BD - Statistics Poland
email: your-email@example.com
description: Statistics Poland
baseurl: "https://PaulinaM1.github.io/hack" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include:
  - _site

collections:
  pages:
    output: true
    permalink: /:path/
  indicators:
    output: true
  goals:
    output: true

prose:
  ignore: ['/assets', '/_includes', '/_layouts', '/scripts', '/sass', '/_posts',  '/_sass', '/_site', '/game', '/indicator', '404.html', '_config.yml', 'index.html', 'search.md' ]
  metadata:
    _metadane_globalne:
      - name: "date"
        field:
          label: "date"
          element: "text"
          placeholder: "YYYY-MM-DD"
          value: CURRENT_DATETIME
      - name: "pl_nazwa_wskaznika"
        field:
            element: text
            label: "Nazwa wskaźnika"
            scope: global
      - name: "pl_cel"
        field:
            element: text
            label: "Cel Zrównoważonego Rozwoju"
            scope: global
      - name: "pl_zadanie"
        field:
            element: textarea
            label: "Zadanie"
            scope: global
      - name: "pl_definicja"
        field:
            element: textarea
            label: "Definicja wskaźnika"
            scope: global
      - name: "pl_jednostka_prezentacji"
        field:
            element: text
            label: "Jednostka prezentacji"
            scope: global
      - name: "pl_dostepne_wymiary"
        field:
            element: textarea
            label: "Dostępne wymiary"
            scope: global
      - name: "pl_wyjasnienia_metodologiczne"
        field:
            element: textarea
            label: "Wyjaśnienia metodologiczne"
            scope: global
      - name: "pl_zrodlo_danych"
        field:
            element: text
            label: "Źródło danych"
            scope: global
      - name: "pl_czestotliwosc_dostępnosc_danych"
        field:
            element: textarea
            label: "Częstotliwość i dostępność danych"
            scope: global
      - name: "pl_uwagi"
        field:
            element: textarea
            label: "Uwagi"
            scope: global
      - name: "en_nazwa_wskaznika"
        field:
            element: text
            label: "Name of the indicator"
            scope: global
      - name: "en_cel"
        field:
            element: text
            label: "Sustainable Development Goal"
            scope: global
      - name: "en_zadanie"
        field:
            element: textarea
            label: "Target"
            scope: global
      - name: "en_definicja"
        field:
            element: textarea
            label: "Definition"
            scope: global
      - name: "en_jednostka_prezentacji"
        field:
            element: text
            label: "Unit"
            scope: global
      - name: "en_dostepne_wymiary"
        field:
            element: textarea
            label: "Available dimensions"
            scope: global
      - name: "en_wyjasnienia_metodologiczne"
        field:
            element: textarea
            label: "Methodological explanations"
            scope: global
      - name: "en_zrodlo_danych"
        field:
            element: text
            label: "Source of data"
            scope: global
      - name: "en_czestotliwosc_dostępnosc_danych"
        field:
            element: textarea
            label: "Data availability"
            scope: global
      - name: "en_uwagi"
        field:
            element: textarea
            label: "Notes"
            scope: global
      - name: "en_graph_title"
        field:
            element: hidden
            label: "graph_title"
            scope: global
      - name: "en_title"
        field:
            element: hidden
            label: "title"
            scope: global
      - name: "en_jednostka"
        field:
            element: hidden
            label: "jednostka"
            scope: global
      - name: "pl_graph_title"
        field:
            element: hidden
            label: "graph_title"
            scope: global
      - name: "pl_title"
        field:
            element: hidden
            label: "title"
            scope: global
      - name: "pl_jednostka"
        field:
            element: hidden
            label: "jednostka"
            scope: global
      - name: "translation_id"
        field:
            element: hidden
            label: "translation_id"
            scope: global
    _metadane_krajowe:
      - name: "date"
        field:
          label: "date"
          element: "text"
          placeholder: "YYYY-MM-DD"
          value: CURRENT_DATETIME
      - name: "pl_nazwa_wskaznika"
        field:
            element: text
            label: "Nazwa wskaźnika"
            scope: global
      - name: "pl_cel"
        field:
            element: text
            label: "Cel Zrównoważonego Rozwoju"
            scope: global
      - name: "pl_priorytet"
        field:
            element: textarea
            label: "Priorytet"
            scope: global
      - name: "pl_definicja"
        field:
            element: textarea
            label: "Definicja wskaźnika"
            scope: global
      - name: "pl_jednostka_prezentacji"
        field:
            element: text
            label: "Jednostka prezentacji"
            scope: global
      - name: "pl_dostepne_wymiary"
        field:
            element: textarea
            label: "Dostępne wymiary"
            scope: global
      - name: "pl_wyjasnienia_metodologiczne"
        field:
            element: textarea
            label: "Wyjaśnienia metodologiczne"
            scope: global
      - name: "pl_zrodlo_danych"
        field:
            element: text
            label: "Źródło danych"
            scope: global
      - name: "pl_czestotliwosc_dostępnosc_danych"
        field:
            element: textarea
            label: "Częstotliwość i dostępność danych"
            scope: global
      - name: "pl_uwagi"
        field:
            element: textarea
            label: "Uwagi"
            scope: global
      - name: "en_nazwa_wskaznika"
        field:
            element: text
            label: "Name of the indicator"
            scope: global
      - name: "en_cel"
        field:
            element: text
            label: "Sustainable Development Goal"
            scope: global
      - name: "en_priorytet"
        field:
            element: textarea
            label: "Priority"
            scope: global
      - name: "en_definicja"
        field:
            element: textarea
            label: "Definition"
            scope: global
      - name: "en_jednostka_prezentacji"
        field:
            element: text
            label: "Unit"
            scope: global
      - name: "en_dostepne_wymiary"
        field:
            element: textarea
            label: "Available dimensions"
            scope: global
      - name: "en_wyjasnienia_metodologiczne"
        field:
            element: textarea
            label: "Methodological explanations"
            scope: global
      - name: "en_zrodlo_danych"
        field:
            element: text
            label: "Source of data"
            scope: global
      - name: "en_czestotliwosc_dostępnosc_danych"
        field:
            element: textarea
            label: "Data availability"
            scope: global
      - name: "en_uwagi"
        field:
            element: textarea
            label: "Notes"
            scope: global
      - name: "en_graph_title"
        field:
            element: hidden
            label: "graph_title"
            scope: global
      - name: "en_title"
        field:
            element: hidden
            label: "title"
            scope: global
      - name: "en_jednostka"
        field:
            element: hidden
            label: "jednostka"
            scope: global
      - name: "pl_graph_title"
        field:
            element: hidden
            label: "graph_title"
            scope: global
      - name: "pl_title"
        field:
            element: hidden
            label: "title"
            scope: global
      - name: "pl_jednostka"
        field:
            element: hidden
            label: "jednostka"
            scope: global
      - name: "translation_id"
        field:
            element: hidden
            label: "translation_id"
            scope: global
